# Generated by Django 4.1.5 on 2023-01-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklog',
            name='arguments',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='task_id',
        ),
        migrations.AddField(
            model_name='tasklog',
            name='args',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
