# Generated by Django 4.1.5 on 2023-01-28 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_tasklog_arguments_remove_tasklog_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklog',
            name='name',
        ),
    ]
